name: Build dylib
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dylib
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dylib-output
          path: build/*.dylib
